### PR TITLE
re-Publish v2.7.7 v3.0.5 and more [release]

### PR DESCRIPTION
**Pull request by JalexChen**
Re-publishing this release since the previous PR did not actually push the new images to Dockerhub

### CODE REVIEW

**Review by mrothstein74 — APPROVED** [review]

**Comment by jgarber623** [comment]
Did this work? I'm still seeing errors in workflows:

> Error response from daemon: manifest for cimg/ruby:2.7.7 not found: manifest unknown: manifest unknown

Relatedly, the most recent `cimg/ruby:2.7*` tagged images on Docker Hub were last published [eight months ago](https://hub.docker.com/r/cimg/ruby/tags?page=1&name=2.7). There _are_ `cimg/ruby:3.1*` tagged images, though…

**Comment by n00dle** [comment]
Looks like a bunch of publishes were skipped because there was no existing tag:
```
Publishing cimg/ruby to Docker Hub production.
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7.7
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7-node
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7.7-node
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7-browsers
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:2.7.7-browsers
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0.5
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0-node
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0.5-node
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0-browsers
The push refers to repository [docker.io/cimg/ruby]
tag does not exist: cimg/ruby:3.0.5-browsers
The push refers to repository [docker.io/cimg/ruby]
```

**Comment by aghecht** [comment]
For the Ruby 3.0.5 images, updating the base Dockerfile to use cimg/base:2022.10 instead of cimgbase:2022.04 broke the docker build. Seems to work fine for Ruby 3.1 though.

**Comment by texpert** [comment]
In the **Build Docker images** [logs](https://circleci.com/api/v1.1/project/github/CircleCI-Public/cimg-ruby/431/output/103/0?file=true&allocation-id=6384f2728e40570ca3fb07ab-0-build%2F658BE9C5):

```
*** Following extensions are not compiled:
dbm:
	Could not be configured. It will not be installed.
	Check ext/dbm/mkmf.log for more details.
openssl:
	Could not be configured. It will not be installed.
	/home/circleci/ruby/ext/openssl/extconf.rb:113: OpenSSL >= 1.0.1, < 3.0.0 or LibreSSL >= 2.5.0 is required
	Check ext/openssl/mkmf.log for more details.
*** Fix the problems, then remove these directories and try again if you want.
make[1]: Leaving directory '/home/circleci/ruby'
```

OpenSSL has been [ported to Ubuntu 22.04](https://github.com/rvm/rvm/issues/5209#issuecomment-1134927685), but not to 22.10.

So the fastest fix is to return to `cimg/base:2022.04`.

The long term fix would be to refactor Ruby installation via `asdf` with `asdf-ruby` plugin, which uses the `ruby-build` utility, taking care of [installing necessary package verseions](https://github.com/rbenv/ruby-build/pull/2096/files)

**Comment by JalexChen** [comment]
hi everyone - thanks for the input here. the issue here is with the ubuntu 22.04 base image that uses openssl3, which Ruby 2.7.x and 3.0.x are not compatible with.

additionally, the 3.1.3 build was using the october version of the base image, which is vulnerable to the OpenSSL CVE and is currently being respun

the build should not be showing as a success when these images aren't built - we'll be taking a look into this. i was able to rebuild the images using another base image

**Comment by Jamie5** [comment]
Does removing the 2.7.x in #101 mean that we won't ever get 2.7.7 images?

**Comment by JalexChen** [comment]
> Does removing the 2.7.x in #101 mean that we won't ever get 2.7.7 images?

https://github.com/CircleCI-Public/cimg-ruby/pull/102

**Comment by Jamie5** [comment]
Oh thank you good to know

**Pull request merged**
