### PR TITLE
Publish v3.1.0

### PR DESCRIPTION
**Pull request by enomotodev**

### CODE REVIEW

**Review by felicianotech — CHANGES_REQUESTED** [review]
Hi. Thank you for the PR.

This looks mostly good. We shouldn't have the base image change though. May you revert the template change and re-run the generate script please?

**Comment by enomotodev** [comment]
@felicianotech Thanks for the review.

I've fixed the parts you pointed out, so please review again.

**Comment by felicianotech** [comment]
Before I can get this merged, I need you to use the `generate-dockerfiles.sh` script as mentioned in the readme. Not manually edit these files.

**Comment by enomotodev** [comment]
@felicianotech Oh, sorry.

I thought build-images.sh should be appended, and I manually appended the generated code.

I've re-committed the generated code as is, so please re-review.

**Review by felicianotech — APPROVED** [review]
Thank you so much. I'm running the pipeline now. Once it passed, the new image will be available within a few minutes.

**Pull request merged**
