### PR TITLE
Publish v3.2.0 [release]

### PR DESCRIPTION
**Pull request by mkusaka**
🎅 < Ho-Ho-Ho!
Ruby3.2 released! 🎉
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

### CODE REVIEW

**Comment by schinery** [comment]
@mkusaka you’ll need to add `[release]` to the end of this PR’s title as it is used by the CI to push the images to Docker if found.

See https://github.com/CircleCI-Public/cimg-ruby#publishing-official-images-for-maintainers-only

**Comment by mkusaka** [comment]
@schinery Thanks! I've just updated. :)

**Comment by schinery** [comment]
> @schinery Thanks! I've just updated. :)

👌🏻

Hopefully now one of the cimgs team can take a look and check all is good.

**Comment by felicianotech** [comment]
Reviewing

**Review by felicianotech — APPROVED** [review]
LGTM

**Pull request merged**
