### PR TITLE
Pub: v2.7.8, v3.0.6, v3.1.4, and more. [release]

### PR DESCRIPTION
**Pull request by schinery**
Generated used ` ./shared/release.sh 2.7.8 3.0.6 3.1.4 3.2.2`.

I've seen there are some other PRs to release individual versions (except 3.1.4 currently) but created this to release them all in one go.

### CODE REVIEW

**Review by ur5us — COMMENTED** [review]
Prior to Ruby 3.2, YJIT was not deemed production grade so it probably shouldn’t be enabled for 2.7, 3.0 & 3.1.

**Comment by schinery** [comment]
> Prior to Ruby 3.2, YJIT was not deemed production grade so it probably shouldn’t be enabled for 2.7, 3.0 & 3.1.

I was thinking this but as it says in the [Dockerfile.template](https://github.com/CircleCI-Public/cimg-ruby/blob/main/Dockerfile.template#L3) “_Do not edit individual Dockerfiles manually_” so left the pre 3.2 images as is.

**Comment by schinery** [comment]
Although I was trying to be helpful and get all the Rubies updated in one go it might be worth getting https://github.com/CircleCI-Public/cimg-ruby/pull/115 to unblock 3.2 while the YJIT deps thing is looked at?

**Comment by BytesGuy** [comment]
YJIT is not enabled by default, we are only building support into the Ruby if users want to enable it (`RUBY_YJIT_ENABLE` is not set in the docker image by default for example). 

YJIT can only be enabled if it was built into the Ruby, so we have to do this as part of the image build, otherwise users cannot use it.

On Ruby versions lower than 3.2 the build ignores the attempt to build YJIT support:

```
docker run -it cimg/ruby:3.1 ruby --enable-yjit -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [aarch64-linux]
```

Versus 3.2 (note `+YJIT`)

```
docker run -it cimg/ruby:3.2 ruby --enable-yjit -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) +YJIT [aarch64-linux]
```

**Comment by schinery** [comment]
Thanks for the explanation @BytesGuy. So this PR is good to review?

**Comment by ryanbourdais** [comment]
At the moment this all looks good to me, I'm going to wait for the remaining open PRs to be closed and merged in first though to allow for those contributors to get credit for their work.

**Comment by schinery** [comment]
PR for the 3.1.4 image https://github.com/CircleCI-Public/cimg-ruby/pull/123

**Pull request closed without merging**
