### PR TITLE
Release v2.7.7 v3.0.5 and more

### PR DESCRIPTION
**Pull request by BytesGuy**
Fixed issue in #97 caused by outdated submodule

### CODE REVIEW

**Comment by schinery** [comment]
@JalexChen are you able to give this a look? 🙏🏻

**Review by felicianotech — APPROVED** [review]

**Comment by schinery** [comment]
@BytesGuy it looks like the merge for this might have skipped [publishing the new images on the CI](https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-ruby/315/workflows/dde0f0fa-f331-420e-9240-d0334b6df047/jobs/430).

**Comment by quintela** [comment]
> @BytesGuy it looks like the merge for this might have skipped [publishing the new images on the CI](https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-ruby/315/workflows/dde0f0fa-f331-420e-9240-d0334b6df047/jobs/430), maybe because the title was missing `[release]` in it? 🤷🏻‍♂️

yy. 💯 that was it

```
#!/bin/bash -eo pipefail
if [ "${CIRCLE_BRANCH}" == "main" ]; then
  
  echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
  
  # an else block will be added in the future for a staging release
  if git log -1 --pretty=%s | grep "\[release\]"; then
    echo "Publishing cimg/ruby to Docker Hub production."
    ./push-images.sh
  else
    echo "Skipping publishing."
  fi
fi
```

outputs:
```
Login Succeeded
Skipping publishing.

```

**Comment by JalexChen** [comment]
commit message used `release` vs `[release]` with brackets. i have a new PR out that also updates our shared submodule CODEOWNERS file. stay tuned for an update

**Comment by quintela** [comment]
suggestion: add  `set -e` to build-images.sh .. some refs failed to build before publishing.

**Pull request merged**
